### ISSUE TITLE
容器无法成功运行

### ISSUE THREAD

**Issue by wangweitung** [SeeDLL-Docker/Hexo#1]
用以下命令运行容器后，log里在循环检查更新，也无法访问hexo http://10.1.1.10:4000

```
sudo docker run -d \
    --name=hexo \
    -p 4000:13389 \
    -e HEXO_SERVER_PORT=13389 \
    -e APP_CHECK_UPDATE=true \
    -e GIT_USER=test \
    -e GIT_EMAIL=test@gmail.com \
    -v ./app1:/app \
    --restart unless-stopped \
    seedll/hexo:latest
```

容器log：
```

***** App directory exists and has content, continuing *****

***** npm install npm-check-updates *****


added 1 package in 3s

***** App directory contains no requnirements.txt file, continuing *****

***** Check Hexo Package Version *****

Checking /app/package.json



All dependencies match the latest package versions :)

Upgrading /app/package.json



All dependencies match the latest package versions :)

***** Update Hexo Package Version *****


up to date, audited 678 packages in 8s


42 packages are looking for funding

  run `npm fund` for details


30 vulnerabilities (1 low, 11 moderate, 15 high, 3 critical)


To address issues that do not require attention, run:

  npm audit fix


Some issues need review, and may require choosing

a different dependency.


Run `npm audit` for details.

***** App .ssh directory exists and has content, continuing *****

***** Running git config, user = test, email = test@gmail.com *****

***** Copying .ssh from App directory and setting permissions *****

***** Contents of public ssh key (for deploy) - *****

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZqmq5V0IeAJbT7wDFNsNIfPdxxRDTd6FNvF1rNJuZUrnv11zY8+72PGBmgtvfj7ProqNj5G6QQ46V9bXZuvdTXTsAAhjLYuBUvms+CosLWIbbPrG6KynyOhkyb0MgyjfxuSvIfRCJcXUjgXax6qYnRpdKB5yHs2FjUsGkXfVXVPPogaSobe9eLiByUJTB91+BRs7BNChe6BtmxdWYf3hOa49i+v8e/Mfwuq9eqRWuRqGwwC3Re5ICWf+rttSlh6qjyAwWIKwOxt6N4RswSDI5uPFv2djLzPVcIvCCdxNZzmpgAEGSGZhWgNwsYVDB+hZCpTrfmzlRJ4pJHBWKACR9RRix9lDhjBzxwiAPeeKZ98vlSbrsvT1LDew4ykXfaXhWoQGRm4f9i//Fnr2fINnH28IOPTiPNbT3Z0U2522lSqXehSz8MsEQckE/k0gMuF2enJZHKAioVOHHHKmoygQUU9ZdkktPphCMVsTuz3FjhKMpLeor2pQLB3sO2MAblZU= root@08e84cb17c9c

***** Set the specified port 13389 *****

***** Starting server on port 13389 *****

INFO  Validating config

INFO  Start processing

FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html

Error: EMFILE: too many open files, watch '/app/source/'

    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)

    at Object.watch (node:fs:2468:36)

    at createFsWatchInstance (/app/node_modules/chokidar/lib/nodefs-handler.js:119:15)

    at setFsWatchListener (/app/node_modules/chokidar/lib/nodefs-handler.js:166:15)

    at NodeFsHandler._watchWithNodeFs (/app/node_modules/chokidar/lib/nodefs-handler.js:331:14)

    at NodeFsHandler._handleDir (/app/node_modules/chokidar/lib/nodefs-handler.js:567:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

    at async NodeFsHandler._addToNodeFs (/app/node_modules/chokidar/lib/nodefs-handler.js:617:16)

    at async /app/node_modules/chokidar/index.js:451:21

    at async Promise.all (index 0)

***** App directory exists and has content, continuing *****

***** App directory contains no requnirements.txt file, continuing *****

***** Check Hexo Package Version *****

Checking /app/package.json



All dependencies match the latest package versions :)

Upgrading /app/package.json



All dependencies match the latest package versions :)

***** Update Hexo Package Version *****


up to date, audited 678 packages in 5s


42 packages are looking for funding

  run `npm fund` for details


30 vulnerabilities (1 low, 11 moderate, 15 high, 3 critical)


To address issues that do not require attention, run:

  npm audit fix


Some issues need review, and may require choosing

a different dependency.


Run `npm audit` for details.

***** App .ssh directory exists and has content, continuing *****

***** Running git config, user = test, email = test@gmail.com *****

***** Copying .ssh from App directory and setting permissions *****

***** Contents of public ssh key (for deploy) - *****

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZqmq5V0IeAJbT7wDFNsNIfPdxxRDTd6FNvF1rNJuZUrnv11zY8+72PGBmgtvfj7ProqNj5G6QQ46V9bXZuvdTXTsAAhjLYuBUvms+CosLWIbbPrG6KynyOhkyb0MgyjfxuSvIfRCJcXUjgXax6qYnRpdKB5yHs2FjUsGkXfVXVPPogaSobe9eLiByUJTB91+BRs7BNChe6BtmxdWYf3hOa49i+v8e/Mfwuq9eqRWuRqGwwC3Re5ICWf+rttSlh6qjyAwWIKwOxt6N4RswSDI5uPFv2djLzPVcIvCCdxNZzmpgAEGSGZhWgNwsYVDB+hZCpTrfmzlRJ4pJHBWKACR9RRix9lDhjBzxwiAPeeKZ98vlSbrsvT1LDew4ykXfaXhWoQGRm4f9i//Fnr2fINnH28IOPTiPNbT3Z0U2522lSqXehSz8MsEQckE/k0gMuF2enJZHKAioVOHHHKmoygQUU9ZdkktPphCMVsTuz3FjhKMpLeor2pQLB3sO2MAblZU= root@08e84cb17c9c

***** Set the specified port 13389 *****

***** Starting server on port 13389 *****

INFO  Validating config

INFO  Start processing

FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html

Error: EMFILE: too many open files, watch '/app/source/'

    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)

    at Object.watch (node:fs:2468:36)

    at createFsWatchInstance (/app/node_modules/chokidar/lib/nodefs-handler.js:119:15)

    at setFsWatchListener (/app/node_modules/chokidar/lib/nodefs-handler.js:166:15)

    at NodeFsHandler._watchWithNodeFs (/app/node_modules/chokidar/lib/nodefs-handler.js:331:14)

    at NodeFsHandler._handleDir (/app/node_modules/chokidar/lib/nodefs-handler.js:567:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

    at async NodeFsHandler._addToNodeFs (/app/node_modules/chokidar/lib/nodefs-handler.js:617:16)

    at async /app/node_modules/chokidar/index.js:451:21

    at async Promise.all (index 0)

***** App directory exists and has content, continuing *****

***** App directory contains no requnirements.txt file, continuing *****

***** Check Hexo Package Version *****

Checking /app/package.json



All dependencies match the latest package versions :)

Upgrading /app/package.json



All dependencies match the latest package versions :)

***** Update Hexo Package Version *****


up to date, audited 678 packages in 5s


42 packages are looking for funding

  run `npm fund` for details


30 vulnerabilities (1 low, 11 moderate, 15 high, 3 critical)


To address issues that do not require attention, run:

  npm audit fix


Some issues need review, and may require choosing

a different dependency.


Run `npm audit` for details.

***** App .ssh directory exists and has content, continuing *****

***** Running git config, user = test, email = test@gmail.com *****

***** Copying .ssh from App directory and setting permissions *****

***** Contents of public ssh key (for deploy) - *****

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZqmq5V0IeAJbT7wDFNsNIfPdxxRDTd6FNvF1rNJuZUrnv11zY8+72PGBmgtvfj7ProqNj5G6QQ46V9bXZuvdTXTsAAhjLYuBUvms+CosLWIbbPrG6KynyOhkyb0MgyjfxuSvIfRCJcXUjgXax6qYnRpdKB5yHs2FjUsGkXfVXVPPogaSobe9eLiByUJTB91+BRs7BNChe6BtmxdWYf3hOa49i+v8e/Mfwuq9eqRWuRqGwwC3Re5ICWf+rttSlh6qjyAwWIKwOxt6N4RswSDI5uPFv2djLzPVcIvCCdxNZzmpgAEGSGZhWgNwsYVDB+hZCpTrfmzlRJ4pJHBWKACR9RRix9lDhjBzxwiAPeeKZ98vlSbrsvT1LDew4ykXfaXhWoQGRm4f9i//Fnr2fINnH28IOPTiPNbT3Z0U2522lSqXehSz8MsEQckE/k0gMuF2enJZHKAioVOHHHKmoygQUU9ZdkktPphCMVsTuz3FjhKMpLeor2pQLB3sO2MAblZU= root@08e84cb17c9c

***** Set the specified port 13389 *****

***** Starting server on port 13389 *****

INFO  Validating config

INFO  Start processing

FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html

Error: EMFILE: too many open files, watch '/app/source/'

    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)

    at Object.watch (node:fs:2468:36)

    at createFsWatchInstance (/app/node_modules/chokidar/lib/nodefs-handler.js:119:15)

    at setFsWatchListener (/app/node_modules/chokidar/lib/nodefs-handler.js:166:15)

    at NodeFsHandler._watchWithNodeFs (/app/node_modules/chokidar/lib/nodefs-handler.js:331:14)

    at NodeFsHandler._handleDir (/app/node_modules/chokidar/lib/nodefs-handler.js:567:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

    at async NodeFsHandler._addToNodeFs (/app/node_modules/chokidar/lib/nodefs-handler.js:617:16)

    at async /app/node_modules/chokidar/index.js:451:21

    at async Promise.all (index 0)

***** App directory exists and has content, continuing *****

***** App directory contains no requnirements.txt file, continuing *****

***** Check Hexo Package Version *****

Checking /app/package.json



All dependencies match the latest package versions :)

Upgrading /app/package.json



All dependencies match the latest package versions :)

***** Update Hexo Package Version *****

```

**Comment by SeeDLL** [comment]
现在容器已经更新了，完全按照最新的容器来设置，就可以正常运行了
